#!/bin/sh /etc/rc.common
# Copyright (C) 2009-2014 OpenWrt.org

START=90
STOP=20
USE_PROCD=1

CRONTAB_ROOT="/etc/crontabs/root"
. /usr/share/libubox/jshn.sh

boot() {
	random=$(tr -dc 1-9 </dev/urandom | head -c 3)
	min=$(((random+1) % 60))
	sed -i '/mdnsd/d' $CRONTAB_ROOT
	echo "$min */2 * * * /etc/init.d/mdnsd restart #restart mdnsd" >> $CRONTAB_ROOT

	start
}

start_service() {
	json_load "$(objReq easyMeshBasic json)"
	json_select EasyMeshBasicP
	json_get_vars enable deviceRole
	[ $enable = "1" -a $deviceRole = "2" ] && {
		log "Skip in easymesh child mode!!"
		exit 0
	}

	procd_open_instance
	procd_set_param command /usr/sbin/mdnsd -debug
	procd_set_param respawn
	procd_close_instance
}

