#!/bin/sh /etc/rc.common

START=35
STOP=85
USE_PROCD=1
. /lib/hummer/network/lan.sh
start_service() {
	master_lan_static_dhcp_obj2uci
	procd_open_instance
	procd_set_param command /usr/sbin/odhcpd
	procd_set_param respawn
	procd_close_instance
}

service_triggers()
{
	procd_add_reload_trigger "dhcp"
}

